export const FETCH_BANNER_DETAILS = 'FETCH_BANNER_DETAILS';
export const FETCH_BANNER_DETAILS_FAILURE = 'FETCH_BANNER_DETAILS_FAILURE';
export const FETCH_BANNER_DETAILS_REQUEST = 'FETCH_BANNER_DETAILS_REQUEST';
